version: 2.1

workflows:
  my_workflow:
    jobs:
      - setup_yorov5:
          context:
            - docker
      - setup_maskdataset:
          context:
            - docker
          requires:
            - setup_yorov5
      - train_maskdataset_with_gpu:
          requires:
            - setup_maskdataset

jobs:
  setup_yorov5:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - run:
          name: Set up YOLOv5 setup_environment
          command: |
            git clone https://github.com/ultralytics/yolov5
            cd yolov5
            pyenv install 3.7.6
            pyenv local 3.7.6
            pip install -qr requirements.txt
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - "yolov5"
  setup_maskdataset:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - run:
          name: Set up MaskDataSet from ROBOFLOW(, which needs registration)
          command:  |
            mkdir MaskDataSet
            cd MaskDataSet
            curl -L "https://public.roboflow.com/ds/9rYgiWaqnY?key=$ROBOFLOW_KEY" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
            echo "train: ../MaskDataSet/train/images" > data.yaml
            echo "val: ../MaskDataSet/valid/images" >> data.yaml
            echo "" >> data.yaml
            echo "nc: 2" >> data.yaml
            echo "names: ['mask', 'no-mask']" >> data.yaml
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - "MaskDataSet"
  train_maskdataset_with_gpu:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run:
          name: Check GPU status
          command:  nvidia-smi
      - attach_workspace:
          at: .
      - run:
          name: Setup up Python environment for YOLOv5
          command: |
            cd yolov5
            pyenv install 3.7.6
            pyenv local 3.7.6
            pip install -qr requirements.txt
            cd ..
      - run:
          name: Train MaskDataSet
          command: |
            cd yolov5
            python train.py --data ../MaskDataSet/data.yaml --cfg yolov5s.yaml --weights yolov5s.pt --batch-size 16 --epochs 10
      - persist_to_workspace:
          root: .
          paths:
            - "yolov5"
            - "MaskDataSet"
