version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: |
          git clone https://github.com/ultralytics/yolov5
          cd yolov5
          pip install -qr requirements.txt
