version: 2.1

workflows:
  my_workflow:
    jobs:
      - setup_yorov5:
          context:
            - docker
      - setup_maskdataset:
          context:
            - docker
      - train_maskdataset_with_gpu:
          requires:
            - setup_yorov5
            - setup_maskdataset

jobs:
  setup_yorov5:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: Clone YOLOv5 resources
          command: |
            git clone https://github.com/ultralytics/yolov5
      - restore_cache:
          keys:
            - pip- {{ .Branch }} - {{ checksum "yolov5/requirements.txt" }}
      - run:
          name: Setup up Python environment for YOLOv5
          command: |
            cd yolov5
            if [ ! -d ~/.pyenv/versions/3.7.11 ]; then
              pyenv install 3.7.11
            fi
            pyenv local 3.7.11
            pip install -r requirements.txt
            cd ..
      - save_cache:
          key: pip- {{ .Branch }} - {{ checksum "yolov5/requirements.txt" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - persist_to_workspace:
          root: .
          paths:
            - "yolov5"
  setup_maskdataset:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - run:
          name: Set up MaskDataSet from ROBOFLOW(, which needs registration)
          command:  |
            mkdir MaskDataSet
            cd MaskDataSet
            curl -L "https://public.roboflow.com/ds/9rYgiWaqnY?key=$ROBOFLOW_KEY" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
            echo "train: ../MaskDataSet/train/images" > data.yaml
            echo "val: ../MaskDataSet/valid/images" >> data.yaml
            echo "" >> data.yaml
            echo "nc: 2" >> data.yaml
            echo "names: ['mask', 'no-mask']" >> data.yaml
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - "MaskDataSet"
  train_maskdataset_with_gpu:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - run:
          name: Check GPU status
          command:  nvidia-smi
      - attach_workspace:
          at: .
      - run:
          name: Check if the commit message includes 'kick-training' to continue this job
          command: |
            COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%s)
            TRIGGER_MATCH_PATTERN="^.*kick-training.*$"
            if [[ ${COMMIT_MESSAGE} =~ ${TRIGGER_MATCH_PATTERN} ]]; then
              echo "Will start MaskDataSet training."
            else
              echo "Will skip MaskDataSet training."
              circleci-agent step halt
            fi
      - restore_cache:
          keys:
            - pip- {{ .Branch }} - {{ checksum "yolov5/requirements.txt" }}
      - run:
          name: Setup up Python environment for YOLOv5
          command: |
            cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
            cd yolov5
            if [ ! -d ~/.pyenv/versions/3.7.11 ]; then
              pyenv install 3.7.11
            fi
            pyenv local 3.7.11
            pip install -r requirements.txt
            cd ..
      - save_cache:
          key: pip- {{ .Branch }} - {{ checksum "yolov5/requirements.txt" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - run:
          name: Train MaskDataSet
          command: |
            cd yolov5
            python train.py --data ../MaskDataSet/data.yaml --cfg yolov5s.yaml --weights yolov5s.pt --batch-size 16 --epochs 10
      - persist_to_workspace:
          root: .
          paths:
            - "yolov5"
            - "MaskDataSet"
